import React from "react"
import Head from "next/head"
import Image from "next/image"
import { useRouter } from "next/router"
import styles from "../styles/Home.module.css"

export default function Home() {
  const router = useRouter()

  const [hasLoaded, setHasLoaded] = React.useState(false)

  React.useEffect(() => {
    if (!router.query || Object.keys(router.query).length === 0) return
    fetch("/api/dynamicData", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(router.query),
    })
      .then((res) => res.json())
      .then((data) => manipulateDOM(data))
  }, [router.query])

  const manipulateDOM = (data) => {
    if (!data) return
    // Make text content updations
    for (const element of data.elements) {
      const domElement = document.querySelector(element.selector)
      if (domElement) {
        domElement.textContent = element.text
      }
    }

    // Make style updates
    for (const element of data.styles) {
      const domElement = document.querySelector(element.selector)
      if (domElement) {
        domElement.setAttribute("style", element.css)
      }
    }

    setHasLoaded(true)
  }

  return (
    <div className={styles.container} style={{ opacity: hasLoaded ? 1 : 0 }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title} id="dynamic-data">
          Welcome to <a href="https://nextjs.com">Next.js!</a>
        </h1>

        <button className={styles.button} id="dynamic-button">
          button
        </button>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
